main:LargestBST.o CBinaryTree.o
	g++ -ggdb -O0 LargestBST.o CBinaryTree.o -o main
LargestBST.o:LargestBST.cpp
	g++ -ggdb -c LargestBST.cpp
CBinaryTree.o:CBinaryTree.cpp
	g++ -ggdb -c CBinaryTree.cpp
clean:
	rm *.o main
